---
title: "A07_G28512359"
author: "JINGSI WU"
date: "10/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quadprog)
```


#Markowitz formulation
```{r cars}
mu_return_vector <- c(0.05, 0.04, 0.06) 
sigma <- matrix(c(0.01, 0.002, 0.005, 
                  0.002, 0.008, 0.006, 
                  0.005, 0.006, 0.012), 
                nrow=3, ncol=3)
D.Matrix <- 2*sigma
d.Vector <- rep(0, 3)
A.Equality <- matrix(c(1,1,1), ncol=1)
A.Matrix <- cbind(A.Equality, mu_return_vector, 
                  diag(3))
b.Vector <- c(1, 0, rep(0, 3))
```


Set expected return from 3.5% to 6%, calculate each least variance under the expected return
```{r pressure, echo=FALSE}
return <-  vector()
var <- vector()
j=1
for(i in seq(0.035, 0.06, 0.0001)) {
  b.Vector[2]=i
  out <- solve.QP(Dmat=D.Matrix, dvec=d.Vector, 
                  Amat=A.Matrix, bvec=b.Vector, 
                  meq=1)
  return[j]= i
  var[j]=out$value
  j = j+1
  }
```
Now plot the data
```{r}
plot(var, return, main = "Efficient Frontier", xlab = "Risk appetite", ylab = "Expected Return", type = "l",col='red')
```

